---
title: "Creating VCALL barplots"
author: "Laura Biggins"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
devtools::load_all()
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Use readr::read_tsv() to import data initially. It should look something like this:

```{r, echo=FALSE}
knitr::kable(head(vcall_eg))
```

# Install and load the library

```{r, eval=FALSE}
devtools::install_github("laurabiggins/VCALLplots")
library(VCALLplots)
```

# Count the vcalls

```{r}
processed_vcalls <- process_vcalls(vcall_eg)
knitr::kable(head(processed_vcalls))
```

To export the count data, use readr::write_csv()

```{r, eval=FALSE}
readr::write_csv(x = processed_vcalls, file = "processed_vcalls.csv")
```

# Create bar plot

The counts can be passed directly to the vcall_barplot function.

```{r, fig.width=7}
vcall_barplot(processed_vcalls)
```

To show the raw_counts instead of percentages, use the y_val parameter.

```{r, fig.width=7}
vcall_barplot(processed_vcalls, y_val = "raw_count")
```
